#!/usr/bin/env python3
# -*- coding: utf-8 -*-
__author__ = 'Erik YU'

STKDAILYTABLES = {
    'stk_daily': {'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'daily', 'spm': True,
                  'kfield': 'ts_code', 'dfield': 'trade_date', 'enable': True, 'loop': True,
                  'fields': ''},
    'stk_weekly': {'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'weekly', 'spm': True,
                   'kfield': 'ts_code', 'dfield': 'trade_date', 'enable': False, 'loop': True,
                   'fields': ''},
    'stk_monthly': {'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'monthly', 'spm': True,
                    'kfield': 'ts_code', 'dfield': 'trade_date', 'enable': False, 'loop': True,
                    'fields': ''},
    'stk_daily_basic': {'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'daily_basic', 'spm': False,
                        'kfield': 'ts_code', 'dfield': 'trade_date', 'enable': False, 'loop': True,
                        'fields': ''},
    'stk_moneyflow': {'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'moneyflow', 'spm': False,
                      'kfield': 'ts_code', 'dfield': 'trade_date', 'enable': False, 'loop': True,
                      'fields': ''},
    'stk_suspend': {'freq': 'M', 'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'suspend', 'fields': '', 'spm': False,
                    'kfield': 'ts_code', 'dfield': 'suspend_date', 'enable': True, 'loop': False,
                    'fields': 'ts_code,suspend_date,resume_date,ann_date,suspend_reason,reason_type'},
    'stk_adj_factor': {'freq': 'M', 'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'adj_factor', 'spm': False,
                       'kfield': 'ts_code', 'dfield': 'trade_date', 'enable': True, 'loop': True,
                       'fields': ''},
    'stk_namechg': {'freq': 'M', 'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'namechange', 'spm': False,
                    'kfield': 'ts_code', 'dfield': 'start_date', 'enable': True, 'loop': False,
                    'fields': ''},
    'stk_income': {'freq': 'M', 'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'income', 'spm': False,
                   'kfield': 'ts_code', 'dfield': 'ann_date', 'enable': True, 'loop': False,
                   'fields': ''},
    'stk_balancesheet': {'freq': 'M', 'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'balancesheet', 'spm': False,
                   'kfield': 'ts_code', 'dfield': 'ann_date', 'enable': True, 'loop': False,
                   'fields': ''},
    'stk_cashflow': {'freq': 'M', 'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'cashflow', 'spm': False,
                         'kfield': 'ts_code', 'dfield': 'ann_date', 'enable': True, 'loop': False,
                         'fields': ''},
    'stk_forecast': {'freq': 'M', 'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'forecast', 'spm': False,
                     'kfield': 'ts_code', 'dfield': 'ann_date', 'enable': True, 'loop': False,
                     'fields': ''},
    'stk_express': {'freq': 'M', 'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'express', 'spm': False,
                     'kfield': 'ts_code', 'dfield': 'ann_date', 'enable': True, 'loop': False,
                     'fields': ''},
    'stk_dividend': {'freq': 'M', 'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'dividend', 'spm': False,
                    'kfield': 'ts_code', 'dfield': 'ann_date', 'enable': True, 'loop': False,
                    'fields': ''},
    'stk_fina_indicator': {'freq': 'M', 'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'fina_indicator', 'spm': False,
                     'kfield': 'ts_code', 'dfield': 'ann_date', 'enable': True, 'loop': False,
                     'fields': ''},
    'stk_fina_audit': {'freq': 'M', 'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'fina_audit', 'spm': False,
                           'kfield': 'ts_code', 'dfield': 'ann_date', 'enable': True, 'loop': False,
                           'fields': ''},
    'stk_fina_mainbz': {'freq': 'M', 'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'fina_mainbz', 'spm': False,
                       'kfield': 'ts_code', 'dfield': 'end_date', 'enable': True, 'loop': False,
                       'fields': ''},
    'stk_disclosure_date': {'freq': 'M', 'btab': 'stk_basic', 'sdate': '19901219', 'tuapi': 'fina_mainbz', 'spm': False,
                        'kfield': 'ts_code', 'dfield': 'ann_date', 'enable': True, 'loop': False,
                        'fields': ''},
}

FUNDDAILYTABLES = {
    'fund_daily': {'sdate': '19901219', 'tuapi': 'fund_daily', 'spm': False, 'kfield': 'ts_code', 'dfield': 'trade_date', 'enable': True, 'loop': True,
                   'fields': ''},
    'fund_nav': {'sdate': '19901219', 'tuapi': 'fund_nav', 'spm': False, 'kfield': 'ts_code', 'dfield': 'end_date', 'enable': True, 'loop': False,
                 'fields': ''},
    'fund_div': {'sdate': '19901219', 'tuapi': 'fund_div', 'spm': False, 'kfield': 'ts_code', 'dfield': 'ann_date', 'enable': True, 'loop': False,
                 'fields': ''},
    'fund_portfolio': {'sdate': '19901219', 'tuapi': 'fund_portfolio', 'spm': False, 'kfield': 'ts_code', 'dfield': 'ann_date', 'enable': False, 'loop': False,
                       'fields': ''},
}

IDXDAILYTABLES = {
    'idx_daily': {'btab': 'idx_basic', 'sdate': '19901219', 'tuapi': 'index_daily', 'spm': True,
                  'kfield': 'ts_code', 'dfield': 'trade_date', 'enable': False, 'loop': True,
                  'fields': ''},
    'idx_weekly': {'btab': 'idx_basic', 'sdate': '19901219', 'tuapi': 'index_weekly', 'spm': True,
                   'kfield': 'ts_code', 'dfield': 'trade_date', 'enable': False, 'loop': True,
                   'fields': ''},
    'idx_monthly': {'btab': 'idx_basic', 'sdate': '19901219', 'tuapi': 'index_monthly', 'spm': True,
                    'kfield': 'ts_code', 'dfield': 'trade_date', 'enable': False, 'loop': True,
                    'fields': ''},
    'idx_daily_basic': {'btab': 'idx_basic', 'sdate': '19901219', 'tuapi': 'index_dailybasic', 'spm': False,
                        'kfield': 'ts_code', 'dfield': 'trade_date', 'enable': False, 'loop': True,
                        'fields': ''},
    'idx_weight': {'btab': 'idx_basic', 'sdate': '19901219', 'tuapi': 'index_weight', 'spm': False,
                   'kfield': 'index_code', 'dfield': 'trade_date', 'enable': True, 'loop': True,
                   'fields': '',
                   'cut': True, 'cfield': 'trade_date', 'clen': 5000},
}

BASICTABLES = {
    'stk_basic': {'params': ({'list_status': 'L'}, {'list_status': 'D'}, {'list_status': 'P'}),
                  'tuapi': 'stock_basic', 'spm': False, 'enable': True,
                  'kfield': 'ts_code', 'ufields': ['delist_date', 'list_status', 'name'],
                  'fields': 'ts_code,symbol,name,area,industry,fullname,enname,market,exchange,list_status,delist_date,list_date,is_hs'},
    'idx_basic': {
        'params': ({'market': 'MSCI'}, {'market': 'CSI'}, {'market': 'SSE'}, {'market': 'SZSE'}, {'market': 'CICC'}, {'market': 'SW'}, {'market': 'OTH'}),
        'tuapi': 'index_basic', 'spm': False, 'enable': True,
        'kfield': 'ts_code', 'ufields': ['exp_date', 'name'],
        'fields': 'ts_code,name,market,publisher,index_type,category,base_date,base_point,list_date,weight_rule,exp_date'},
    'idx_concept': {'params': ({'src': 'ts'},),
                    'tuapi': 'concept', 'spm': False, 'enable': True,
                    'kfield': 'code', 'ufields': [],
                    'fields': ''},
    'fund_basic': {'params': ({'market': 'E'}, {'market': 'O'}),
                   'tuapi': 'fund_basic', 'spm': False, 'enable': True,
                   'kfield': 'ts_code', 'ufields': ['due_date', 'delist_date', 'status'],
                   'fields': ''},
    'fund_company': {'params': ({},),
                     'tuapi': 'fund_company', 'spm': False, 'enable': True,
                     'kfield': 'name', 'ufields': ['org_code', 'credit_code'],
                     'fields': ''},
    'stk_company': {'params': ({'exchange': 'SSE'}, {'exchange': 'SZSE'}),
                    'tuapi': 'stock_company', 'spm': False, 'enable': True,
                    'kfield': 'ts_code', 'ufields': ['chairman'],
                    'fields': ''},
}
