#DROP TABLE IF EXISTS `stk_income`;
CREATE TABLE `stk_income` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ts_code` varchar(9) NOT NULL COMMENT 'TS代码',
  `ann_date` char(8) DEFAULT NULL COMMENT '公告日期',
  `f_ann_date` char(8) DEFAULT NULL  COMMENT '实际公告日期，即发生过数据变更的最终日期',
  `end_date` char(8) DEFAULT NULL COMMENT '报告期',
  `report_type` char(2) DEFAULT NULL COMMENT '报告类型stk_enum.report_type',
  `comp_type` char(1) DEFAULT NULL COMMENT '公司类型stk_enum.comp_type',
  `basic_eps` float DEFAULT NULL COMMENT '基本每股收益',
  `diluted_eps` float DEFAULT NULL COMMENT '稀释每股收益',
  `total_revenue` float DEFAULT NULL COMMENT '营业总收入',
  `revenue` float DEFAULT NULL COMMENT '营业收入',
  `int_income` float DEFAULT NULL COMMENT '利息收入',
  `prem_earned` float DEFAULT NULL COMMENT '已赚保费',
  `comm_income` float DEFAULT NULL COMMENT '手续费及佣金收入',
  `n_commis_income` float DEFAULT NULL COMMENT '手续费及佣金净收入',
  `n_oth_income` float DEFAULT NULL COMMENT '其他经营净收益',
  `n_oth_b_income` float DEFAULT NULL COMMENT '加:其他业务净收益',
  `prem_income` float DEFAULT NULL COMMENT '保险业务收入',
  `out_prem` float DEFAULT NULL COMMENT '减:分出保费',
  `une_prem_reser` float DEFAULT NULL COMMENT '提取未到期责任准备金',
  `reins_income` float DEFAULT NULL COMMENT '其中:分保费收入',
  `n_sec_tb_income` float DEFAULT NULL COMMENT '代理买卖证券业务净收入',
  `n_sec_uw_income` float DEFAULT NULL COMMENT '证券承销业务净收入',
  `n_asset_mg_income` float DEFAULT NULL COMMENT '受托客户资产管理业务净收入',
  `oth_b_income` float DEFAULT NULL COMMENT '其他业务收入',
  `fv_value_chg_gain` float DEFAULT NULL COMMENT '加:公允价值变动净收益',
  `invest_income` float DEFAULT NULL COMMENT '加:投资净收益',
  `ass_invest_income` float DEFAULT NULL COMMENT '其中:对联营企业和合营企业的投资收益',
  `forex_gain` float DEFAULT NULL COMMENT '加:汇兑净收益',
  `total_cogs` float DEFAULT NULL COMMENT '营业总成本',
  `oper_cost` float DEFAULT NULL COMMENT '减:营业成本',
  `int_exp` float DEFAULT NULL COMMENT '减:利息支出',
  `comm_exp` float DEFAULT NULL COMMENT '减:手续费及佣金支出',
  `biz_tax_surchg` float DEFAULT NULL COMMENT '减:营业税金及附加',
  `sell_exp` float DEFAULT NULL COMMENT '减:销售费用',
  `admin_exp` float DEFAULT NULL COMMENT '减:管理费用',
  `fin_exp` float DEFAULT NULL COMMENT '减:财务费用',
  `assets_impair_loss` float DEFAULT NULL COMMENT '减:资产减值损失',
  `prem_refund` float DEFAULT NULL COMMENT '退保金',
  `compens_payout` float DEFAULT NULL COMMENT '赔付总支出',
  `reser_insur_liab` float DEFAULT NULL COMMENT '提取保险责任准备金',
  `div_payt` float DEFAULT NULL COMMENT '保户红利支出',
  `reins_exp` float DEFAULT NULL COMMENT '分保费用',
  `oper_exp` float DEFAULT NULL COMMENT '营业支出',
  `compens_payout_refu` float DEFAULT NULL COMMENT '减:摊回赔付支出',
  `insur_reser_refu` float DEFAULT NULL COMMENT '减:摊回保险责任准备金',
  `reins_cost_refund` float DEFAULT NULL COMMENT '减:摊回分保费用',
  `other_bus_cost` float DEFAULT NULL COMMENT '其他业务成本',
  `operate_profit` float DEFAULT NULL COMMENT '营业利润',
  `non_oper_income` float DEFAULT NULL COMMENT '加:营业外收入',
  `non_oper_exp` float DEFAULT NULL COMMENT '减:营业外支出',
  `nca_disploss` float DEFAULT NULL COMMENT '其中:减:非流动资产处置净损失',
  `total_profit` float DEFAULT NULL COMMENT '利润总额',
  `income_tax` float DEFAULT NULL COMMENT '所得税费用',
  `n_income` float DEFAULT NULL COMMENT '净利润(含少数股东损益)',
  `n_income_attr_p` float DEFAULT NULL COMMENT '净利润(不含少数股东损益)',
  `minority_gain` float DEFAULT NULL COMMENT '少数股东损益',
  `oth_compr_income` float DEFAULT NULL COMMENT '其他综合收益',
  `t_compr_income` float DEFAULT NULL COMMENT '综合收益总额',
  `compr_inc_attr_p` float DEFAULT NULL COMMENT '归属于母公司(或股东)的综合收益总额',
  `compr_inc_attr_m_s` float DEFAULT NULL COMMENT '归属于少数股东的综合收益总额',
  `ebit` float DEFAULT NULL COMMENT '息税前利润',
  `ebitda` float DEFAULT NULL COMMENT '息税折旧摊销前利润',
  `insurance_exp` float DEFAULT NULL COMMENT '保险业务支出',
  `undist_profit` float DEFAULT NULL COMMENT '年初未分配利润',
  `distable_profit` float DEFAULT NULL COMMENT '可分配利润',
  `update_flag` varchar(10) DEFAULT NULL COMMENT '更新标识',
  PRIMARY KEY (`id`),
  KEY `stk_inc_tc` (`ts_code`)
) ENGINE=InnoDB;

