#DROP TABLE IF EXISTS `fund_basic`;
CREATE TABLE `fund_basic` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ts_code` varchar(20) NOT NULL COMMENT 'TS代码',
  `name` varchar(200) DEFAULT NULL COMMENT '简称',
  `management` varchar(200) DEFAULT NULL COMMENT '管理人',
  `custodian` varchar(200) DEFAULT NULL COMMENT '托管人',
  `fund_type` varchar(50) DEFAULT NULL COMMENT '投资类型',
  `found_date` char(8) DEFAULT NULL COMMENT '成立日期',
  `due_date` char(8) DEFAULT NULL COMMENT '到期日期',
  `list_date` char(8) DEFAULT NULL COMMENT '上市时间',
  `issue_date` char(8) DEFAULT NULL COMMENT '发行日期',
  `delist_date` char(8) DEFAULT NULL COMMENT '退市日期',
  `issue_amount` float DEFAULT NULL COMMENT '发行份额(亿)',
  `m_fee` float DEFAULT NULL COMMENT '管理费',
  `c_fee` float DEFAULT NULL COMMENT '托管费',
  `duration_year` float DEFAULT NULL COMMENT '存续期',
  `p_value` float DEFAULT NULL COMMENT '面值',
  `min_amount` float DEFAULT NULL COMMENT '起点金额(万元)',
  `exp_return` float DEFAULT NULL COMMENT '预期收益率',
  `benchmark` varchar(50) DEFAULT NULL COMMENT '业绩比较基准',
  `status` varchar(10) DEFAULT NULL COMMENT '存续状态D摘牌 I发行 L已上市',
  `invest_type` varchar(50) DEFAULT NULL COMMENT '投资风格',
  `type` varchar(50) DEFAULT NULL COMMENT '基金类型',
  `trustee` varchar(200) DEFAULT NULL COMMENT '受托人',
  `purc_startdate` char(8) DEFAULT NULL COMMENT '日常申购起始日',
  `redm_startdate` char(8) DEFAULT NULL COMMENT '日常赎回起始日',
  `market` varchar(10) DEFAULT NULL COMMENT 'E场内O场外',
  `del` tinyint(3) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `f_fb_code` (`ts_code`)
) ENGINE=InnoDB;