DROP TABLE IF EXISTS `stk_moneyflow`;
CREATE TABLE `stk_moneyflow` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ts_code` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'TS代码',
  `trade_date` char(8) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '交易日期',
  `buy_sm_vol` int(10) DEFAULT NULL COMMENT '小单买入量（手）',
  `buy_sm_amount` decimal(20,4) DEFAULT NULL COMMENT '小单买入金额（万元）',
  `sell_sm_vol` int(10) DEFAULT NULL COMMENT '小单卖出量（手）',
  `sell_sm_amount` decimal(20,4) DEFAULT NULL COMMENT '小单卖出金额（万元）',
  `buy_md_vol` int(10) DEFAULT NULL COMMENT '中单买入量（手）',
  `buy_md_amount` decimal(20,4) DEFAULT NULL COMMENT '中单买入金额（万元）',
  `sell_md_vol` int(10) DEFAULT NULL COMMENT '中单卖出量（手）',
  `sell_md_amount` decimal(20,4) DEFAULT NULL COMMENT '中单卖出金额（万元）',
  `buy_lg_vol` int(10) DEFAULT NULL COMMENT '大单买入量（手）',
  `buy_lg_amount` decimal(20,4) DEFAULT NULL COMMENT '大单买入金额（万元）',
  `sell_lg_vol` int(10) DEFAULT NULL COMMENT '大单卖出量（手）',
  `sell_lg_amount` decimal(20,4) DEFAULT NULL COMMENT '大单卖出金额（万元）',
  `buy_elg_vol` int(10) DEFAULT NULL COMMENT '特大单买入量（手）',
  `buy_elg_amount` decimal(20,4) DEFAULT NULL COMMENT '特大单买入金额（万元）',
  `sell_elg_vol` int(10) DEFAULT NULL COMMENT '特大单卖出量（手）',
  `sell_elg_amount` decimal(20,4) DEFAULT NULL COMMENT '特大单卖出金额（万元）',
  `net_mf_vol` int(10) DEFAULT NULL COMMENT '净流入量（手）',
  `net_mf_amount` decimal(20,4) DEFAULT NULL COMMENT '净流入额（万元）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `stk_mf_tctd` (`ts_code`,`trade_date`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;